-- AlterTable
ALTER TABLE "User" RENAME COLUMN "coins" TO "cash";
ALTER TABLE "User" ADD COLUMN     "bank" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastMessageDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
